In [1]:
import pandas as pd
import numpy as np
import csv
import math
import os,sys
from scipy import stats
aa=pd.read_csv("Earthquakes.csv",sep=";")
earthquakes=np.array(aa)
earthquakes

array([[1.000e+00, 0.000e+00, 0.000e+00, ..., 4.100e+00, 7.000e+00,
        0.000e+00],
       [2.000e+00, 0.000e+00, 0.000e+00, ..., 4.400e+00, 7.000e+00,
        0.000e+00],
       [3.000e+00, 0.000e+00, 0.000e+00, ..., 4.000e+00, 7.000e+00,
        0.000e+00],
       ...,
       [6.571e+03, 4.000e+00, 0.000e+00, ..., 4.800e+00, 2.000e+00,
        0.000e+00],
       [6.572e+03, 3.000e+00, 0.000e+00, ..., 5.200e+00, 2.000e+00,
        0.000e+00],
       [6.573e+03, 2.000e+00, 0.000e+00, ..., 4.400e+00, 2.000e+00,
        0.000e+00]])

In [2]:
liste=[]
data1=np.array(earthquakes[0:20,3])
data2=np.array(earthquakes[0:20,5])
data3=np.array(earthquakes[0:20,7])
data4=np.array(earthquakes[0:20,12])

liste.append(data1)
liste.append(data2)
liste.append(data3)
liste.append(data4)
my_list=np.array(liste)
print(my_list)

[[  0.      0.      0.      0.      0.      0.      0.      0.      0.
    0.      0.      0.      0.      0.      0.      0.      0.      0.
    0.      0.   ]
 [374.341 376.878 372.003 356.846 364.171 360.535 371.958 369.653  38.893
  373.773 358.861 374.635 370.201 376.546 375.318 390.388  38.357 357.018
  376.883 421.821]
 [  7.02   10.27   78.07   42.77   14.86   36.68   50.33    6.93   11.62
   10.53   28.49   15.29   10.      4.5    17.58    7.52   10.05    6.25
   10.63    5.81 ]
 [  4.1     4.4     4.      4.5     4.1     5.2     4.8     4.3     4.2
    4.8     4.9     4.3     4.1     4.5     4.6     4.5     4.1     4.1
    4.1     4.   ]]


In [3]:
earthquakes=earthquakes.astype(int)
earthquakes

array([[   1,    0,    0, ...,    4,    7,    0],
       [   2,    0,    0, ...,    4,    7,    0],
       [   3,    0,    0, ...,    4,    7,    0],
       ...,
       [6571,    4,    0, ...,    4,    2,    0],
       [6572,    3,    0, ...,    5,    2,    0],
       [6573,    2,    0, ...,    4,    2,    0]])

In [4]:
print(earthquakes[earthquakes > 4.5])

[374  35   7 ...  37  28  10]


In [6]:
earthquakes[0] = 0
new_earthquakes=earthquakes
new_earthquakes

array([[   0,    0,    0, ...,    0,    0,    0],
       [   2,    0,    0, ...,    4,    7,    0],
       [   3,    0,    0, ...,    4,    7,    0],
       ...,
       [6571,    4,    0, ...,    4,    2,    0],
       [6572,    3,    0, ...,    5,    2,    0],
       [6573,    2,    0, ...,    4,    2,    0]])

In [12]:
np.savetxt('Earthquakes_new.csv',new_earthquakes,delimiter=";")